name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint -- --max-warnings=0
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run jest
        run: npm run test -- --coverage
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2
        with:
          build: npm run build
          start: npm start
        env: 
          DB_HOST: ${{ secrets.INTEGRATION_DB_HOST }}
          DB_PORT: ${{ secrets.INTEGRATION_DB_PORT }}
          DB_USERNAME: ${{ secrets.INTEGRATION_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.INTEGRATION_DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.INTEGRATION_DB_DATABASE }}
      - name: Upload video to S3
        run:
          aws s3 cp /home/runner/work/SD-track-NFT-transactions/SD-track-NFT-transactions/cypress/videos/tracker.cy.tsx.mp4 s3://${{ secrets.AWS_S3_BUCKET_VIDEOS }}/$GITHUB_SHA.mp4
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}