name: linter
#js linter

on:
  push:
    branches:
      - "main"
      - "FEAT_**"
      - "FIX_**"
  pull_request:
    branches: 
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint -- --max-warnings=0